### ISSUE TITLE
Felix crashing with timeouts followed by Address already in use

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico-docker-prototype#21] opened 2015-01-21 01:52 UTC
With latest Felix binary: 10.3-rc1, I'm seeing this on my second node but @tomdee is not (maybe it's just intermittent now).  Felix is cyclicly dying and never seems to recover:

```
2015-01-21 01:36:14,775 [ERROR] calico.felix.felix 70: Felix starting
2015-01-21 01:36:14,778 [INFO] calico.felix.fsocket 87: Creating socket to entity 172.17.8.102:9902
2015-01-21 01:36:14,779 [INFO] calico.felix.fsocket 87: Creating socket to entity 172.17.8.102:9901
2015-01-21 01:36:14,779 [INFO] calico.felix.fsocket 87: Creating socket to entity 172.17.8.102:9905
2015-01-21 01:36:14,780 [INFO] calico.felix.fsocket 87: Creating socket to entity 172.17.8.102:9906
2015-01-21 01:36:14,782 [INFO] calico.felix.felix 191: Do total resync - ID : add757f3-0cbc-404b-ad03-6b8b95a59d18
2015-01-21 01:36:14,782 [INFO] calico.felix.fsocket 111: Sent RESYNCSTATE(add757f3-0cbc-404b-ad03-6b8b95a59d18) on socket EP REQ
2015-01-21 01:36:19,937 [INFO] calico.felix.fsocket 111: Sent HEARTBEAT on socket ACL REQ
2015-01-21 01:36:55,029 [WARNING] calico.felix.felix 635: Socket EP REP timed out
2015-01-21 01:36:55,030 [INFO] calico.felix.fsocket 87: Creating socket to entity 172.17.8.102:9902
2015-01-21 01:36:55,030 [ERROR] calico.felix.felix 751: Felix exiting after uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/calico/felix/felix.py", line 742, in main
    agent.run()
  File "/usr/lib/python2.7/dist-packages/calico/felix/felix.py", line 657, in run
    sock.communicate(self.hostname, self.zmq_context)
  File "/usr/lib/python2.7/dist-packages/calico/felix/fsocket.py", line 93, in communicate
    self._zmq.bind("tcp://%s:%s" % (self.config.LOCAL_ADDR, self.port))
  File "socket.pyx", line 434, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:3928)
  File "checkrc.pxd", line 21, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:6058)
ZMQError: Address already in use
Info: Running a benchmark to measure system clock frequency...
Info: Finished RDTSC test. To prevent the startup delay from this benchmark, set the environment variable RDTSC_FREQUENCY to 2149 on this system. This value is dependent upon the CPU clock speed and architecture and should be determined separately for each server.
2015-01-21 01:36:59,464 [ERROR] calico.felix.felix 70: Felix starting
2015-01-21 01:36:59,467 [INFO] calico.felix.fsocket 87: Creating socket to entity 172.17.8.102:9902
2015-01-21 01:36:59,467 [INFO] calico.felix.fsocket 87: Creating socket to entity 172.17.8.102:9901
2015-01-21 01:36:59,468 [INFO] calico.felix.fsocket 87: Creating socket to entity 172.17.8.102:9905
2015-01-21 01:36:59,469 [INFO] calico.felix.fsocket 87: Creating socket to entity 172.17.8.102:9906
2015-01-21 01:36:59,469 [INFO] calico.felix.felix 191: Do total resync - ID : 69e2f0c4-3048-4e30-9152-71fbceea7ce3
2015-01-21 01:36:59,469 [INFO] calico.felix.fsocket 111: Sent RESYNCSTATE(69e2f0c4-3048-4e30-9152-71fbceea7ce3) on socket EP REQ
2015-01-21 01:37:04,620 [INFO] calico.felix.fsocket 111: Sent HEARTBEAT on socket ACL REQ
```

**Comment by Lukasa** [comment] 2015-01-21 08:44
EADDRINUSE is a weird thing to see with ZMQ, as I'm pretty sure it sets SO_REUSEADDR on its sockets. That suggests that one of two things:

1. There's another process hanging on to those sockets. Unlikely, given that Felix was able to restart them and bind them just fine a mere 4 seconds later, but it's certainly possible.
2. More likely is that the non-blocking close took long enough that the socket was not actually unbound, so the Linux kernel forbade us from re-binding it. That's possible: the close and re-bind are quite close together.

Either way, we need to come up with a solution for handling socket-binding throwing EADDRINUSE. At startup it's probably best we just quit with a suitable warning. When rebuilding the sockets it might be a bit better to wait.

I suspect this issue is seen primarily on slower systems that take a long time to do the close on the background thread, which is why we haven't seen it before now.

**Comment by plwhite** [comment] 2015-01-21 09:10
This is an issue with Felix, not the plugin. It's pretty benign in practice though a bit embarrassing.

It's also a duplicate of this issue https://github.com/Metaswitch/calico/issues/97

**Closed by plwhite** 2015-01-21 09:10 UTC
